apiVersion: v1
Kind: ConfigMap
metadata:
  name: config
data:
  TELOXIDE_TOKEN: # Telegram bot token
  OWNER_ID: # Telegram user ID, only id matches can bot switch the chat to working mode
  TELEGRAM_API_ID: # Telegram API ID
  TELEGRAM_API_HASH: # Telegram API hash
---
apiVersion: v1
kind: Pod
metadata:
  name: sync-bot
spec:
  volumes:
    - name: cache
      persistentVolumeClaim:
        claimName: cache
    - hostPath:
        path: <OUTPUT_DIR> # Path to the output directory on the host
        type: Directory
      name: output
  containers:
    - name: server
      image: server
      envFrom:
        - configMapRef:
            name: config
            optional: false
      volumeMounts:
        - mountPath: /app/data
          name: cache
    - name: bot
      image: bot
      args:
        - -l
        - http://server:8081
      envFrom:
        - configMapRef:
            name: config
            optional: false
      volumeMounts:
        - mountPath: /app/output
          name: output
        - mountPath: /app/data
          name: cache
