apiVersion: v1
Kind: ConfigMap
metadata:
  name: config
data:
  TELOXIDE_TOKEN: # Telegram bot token
  BYPASS_USERS: # Telegram user IDs, only id or dynamic pwd matches can bot switch the chat to working mode
  TELEGRAM_API_ID: # Telegram API ID
  TELEGRAM_API_HASH: # Telegram API hash
---
apiVersion: v1
kind: Pod
metadata:
  name: sync-bot
spec:
  volumes:
    - name: data
      hostPath:
        path: <DATA_DIR> # Path to the data directory on the host
        type: Directory

  containers:
    - name: server
      image: server
      envFrom:
        - configMapRef:
            name: config
            optional: false
      volumeMounts:
        - mountPath: /app/data
          name: data

    - name: bot
      image: bot:0.5.0
      args:
        - run
        - -d
        - /app/data
        - -l
        - http://server:8081
        - -f10
        - -F-10
      envFrom:
        - configMapRef:
            name: config
      volumeMounts:
        - mountPath: /app/data
          name: data
