apiVersion: v1
kind: PersistentVolume
metadata:
  name: sync-bot-pv
spec:
  capacity:
    storage: 128Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /run/media/louis/Btrfs/sync-bot # Path to the data directory on the host
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - louis # Hostname of the node
