apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sync-bot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: ""
  volumeName: sync-bot-pv
