FROM docker.io/alpine:latest AS server_builder

COPY start.sh .

RUN apk update \
    && apk add --no-cache --purge alpine-sdk linux-headers git zlib-dev openssl-dev gperf cmake ninja

RUN git clone --recursive https://github.com/tdlib/telegram-bot-api.git \
    && cd telegram-bot-api \
    && rm -rf build \
    && mkdir build \
    && cd build \
    && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. .. \
    && ninja install \
    && cd ../.. \
    && ls -l telegram-bot-api/bin/telegram-bot-api*

########################################

FROM docker.io/alpine:latest AS server

WORKDIR /app

COPY start.sh .
COPY --from=server_builder /telegram-bot-api/bin/telegram-bot-api .

RUN apk update \
    && apk add --no-cache --purge bash openssl zlib libstdc++   \
    && chmod +x ./start.sh

EXPOSE 8081

ENTRYPOINT ["./start.sh"]
