//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_id: String,
    pub file_name: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub state: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub transport_state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_handle::Entity")]
    FileHandle,
}

impl Related<super::file_handle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileHandle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
