//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_handle")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub msg_id: i32,
    pub file_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_state::Entity",
        from = "Column::FileId",
        to = "super::file_state::Column::FileId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    FileState,
}

impl Related<super::file_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
