FROM docker.io/rust:1.85.0-alpine AS bot_builder

RUN apk update \
    && apk add --no-cache --purge libc-dev openssl-dev openssl-libs-static pkgconfig

WORKDIR /work

COPY . .

RUN cargo fetch
RUN cargo build --release

########################################

FROM docker.io/alpine:latest AS bot

RUN apk update \
    && apk add --no-cache --purge bash

WORKDIR /app

COPY --from=bot_builder /work/target/release/telegram_sync_bot /app/

STOPSIGNAL SIGINT

ENTRYPOINT ["/app/telegram_sync_bot", "-o", "output"]
