//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "file_state"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub file_id: String,
    pub state: String,
    pub transport_state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FileId,
    State,
    TransportState,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FileId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FileHandle,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FileId => ColumnType::String(StringLen::None).def(),
            Self::State => ColumnType::custom("enum_text").def(),
            Self::TransportState => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FileHandle => Entity::has_many(super::file_handle::Entity).into(),
        }
    }
}

impl Related<super::file_handle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileHandle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
