//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "file_handle"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub chat_id: i64,
    pub msg_id: i32,
    pub file_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ChatId,
    MsgId,
    FileId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ChatId,
    MsgId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i32);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FileState,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ChatId => ColumnType::BigInteger.def(),
            Self::MsgId => ColumnType::Integer.def(),
            Self::FileId => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FileState => Entity::belongs_to(super::file_state::Entity)
                .from(Column::FileId)
                .to(super::file_state::Column::FileId)
                .into(),
        }
    }
}

impl Related<super::file_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
